import type { APIRoute } from 'astro';

/**
 * Custom sitemap.xml endpoint
 * 
 * This endpoint generates a sitemap index that references the static sitemap
 * generated by @astrojs/sitemap. The integration generates sitemap-index.xml
 * which contains references to all numbered sitemap files (sitemap-0.xml, etc.).
 * 
 * Note: Dynamic SSR routes (/@[handle] and /@[handle]/[postId]) cannot be
 * auto-discovered by @astrojs/sitemap since they're rendered on-demand.
 * These routes will be discovered by crawlers through links on your site.
 * 
 * If you need to explicitly include specific handles/posts in the sitemap,
 * you can extend this endpoint to fetch them and add additional <sitemap>
 * entries pointing to custom sitemap files.
 */
export const GET: APIRoute = ({ site }) => {
  // Handle site as URL object or string
  const siteUrl = site 
    ? (typeof site === 'string' ? site : site.href).replace(/\/$/, '')
    : 'https://getorbyt.com';
  
  // Generate sitemap index XML that references the generated sitemap-index.xml
  // This allows robots.txt to reference /sitemap.xml while the actual
  // sitemap structure is managed by @astrojs/sitemap
  const sitemapIndex = `<?xml version="1.0" encoding="UTF-8"?>
<sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
  <sitemap>
    <loc>${siteUrl}/sitemap-index.xml</loc>
    <lastmod>${new Date().toISOString().split('T')[0]}</lastmod>
  </sitemap>
</sitemapindex>`;

  return new Response(sitemapIndex, {
    headers: {
      'Content-Type': 'application/xml; charset=utf-8',
      'Cache-Control': 'public, max-age=3600', // Cache for 1 hour
    },
  });
};
