#!/usr/bin/env bash
# Downloads Klee One (400) subset woff2 files from Google Fonts and writes
# public/css/klee-one.css with same-origin URLs. Re-run when bumping the font.
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUT_DIR="$ROOT/public/fonts/Klee_One"
CSS_OUT="$ROOT/public/css/klee-one.css"
UA='Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36'
mkdir -p "$OUT_DIR"
CSS=$(curl -sL 'https://fonts.googleapis.com/css2?family=Klee+One:wght@400&display=swap' -H "User-Agent: ${UA}")
while IFS= read -r url; do
  [[ -n "$url" ]] || continue
  fn=$(basename "$url")
  out="${OUT_DIR}/${fn}"
  if [[ ! -f "$out" ]]; then
    echo "fetch ${fn}"
    curl -sL "$url" -o "$out"
  fi
done < <(echo "$CSS" | grep -oE 'https://fonts\.gstatic\.com[^)]+\.woff2' | sort -u)
{
  echo '/* Generated by scripts/fetch-klee-one-fonts.sh — do not edit by hand. */'
  echo
  echo "$CSS" \
    | sed -E 's#https://fonts.gstatic.com/s/kleeone/[^/]+/#/fonts/Klee_One/#g' \
    | sed 's/font-display: swap/font-display: fallback/g'
} > "$CSS_OUT"
echo "Wrote ${CSS_OUT} ($(grep -c '@font-face' "$CSS_OUT") @font-face blocks)"
